// ── WAEC Physics Questions (2020–2025) ───────────────────────────────────────
// Add this file to: lib/src/features/quiz/screens/
// Then import it wherever needed:
// import 'physics_questions.dart';

import 'question_model.dart';

// ══════════════════════════════════════════════════════════════════════════════
// OBJECTIVE (MCQ) QUESTIONS
// ══════════════════════════════════════════════════════════════════════════════

// ── WAEC Physics 2020 ─────────────────────────────────────────────────────────
const List<Question> physicsQuestions2020 = [
  Question(question: 'Which of the following is a scalar quantity?', options: ['Force', 'Velocity', 'Speed', 'Acceleration'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'The SI unit of electric current is:', options: ['Volt', 'Ohm', 'Ampere', 'Watt'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'A body is in equilibrium when the net force acting on it is:', options: ['Maximum', 'Minimum', 'Zero', 'Constant'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'The speed of light in a vacuum is approximately:', options: ['3×10⁶ m/s', '3×10⁸ m/s', '3×10¹⁰ m/s', '3×10⁴ m/s'], correctIndex: 1, subject: 'Physics', year: 2020),
  Question(question: 'Which type of wave requires a material medium to propagate?', options: ['Radio waves', 'Light waves', 'Sound waves', 'X-rays'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'The law that states "for every action, there is an equal and opposite reaction" is:', options: ['Newton\'s First Law', 'Newton\'s Second Law', 'Newton\'s Third Law', 'Law of Gravitation'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'The unit of power is:', options: ['Joule', 'Newton', 'Watt', 'Pascal'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'Which of the following converts mechanical energy to electrical energy?', options: ['Motor', 'Generator', 'Transformer', 'Battery'], correctIndex: 1, subject: 'Physics', year: 2020),
  Question(question: 'The process by which a solid changes directly to gas is called:', options: ['Evaporation', 'Condensation', 'Sublimation', 'Solidification'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'Ohm\'s Law states that current is:', options: ['Directly proportional to resistance', 'Inversely proportional to voltage', 'Directly proportional to voltage', 'Independent of voltage'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'A convex lens is also known as a:', options: ['Diverging lens', 'Converging lens', 'Concave lens', 'Plane lens'], correctIndex: 1, subject: 'Physics', year: 2020),
  Question(question: 'The acceleration due to gravity on Earth is approximately:', options: ['9.8 m/s²', '9.8 m/s', '10 m/s³', '8.9 m/s²'], correctIndex: 0, subject: 'Physics', year: 2020),
  Question(question: 'Which of the following is NOT a form of energy?', options: ['Kinetic energy', 'Potential energy', 'Nuclear energy', 'Mass'], correctIndex: 3, subject: 'Physics', year: 2020),
  Question(question: 'The phenomenon of light bending when passing from one medium to another is:', options: ['Reflection', 'Refraction', 'Diffraction', 'Dispersion'], correctIndex: 1, subject: 'Physics', year: 2020),
  Question(question: 'Pressure is defined as:', options: ['Force × Area', 'Force / Area', 'Mass / Volume', 'Weight / Mass'], correctIndex: 1, subject: 'Physics', year: 2020),
  Question(question: 'The device used to measure atmospheric pressure is:', options: ['Thermometer', 'Hydrometer', 'Barometer', 'Manometer'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'When two resistors R₁ and R₂ are connected in series, the total resistance is:', options: ['R₁ × R₂', 'R₁ + R₂', 'R₁ / R₂', '(R₁ × R₂)/(R₁ + R₂)'], correctIndex: 1, subject: 'Physics', year: 2020),
  Question(question: 'The kinetic energy of a body of mass m moving with velocity v is:', options: ['mv', 'mv²', '½mv²', '2mv²'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'Which colour of light has the highest frequency?', options: ['Red', 'Yellow', 'Green', 'Violet'], correctIndex: 3, subject: 'Physics', year: 2020),
  Question(question: 'The SI unit of frequency is:', options: ['Decibel', 'Hertz', 'Metre', 'Second'], correctIndex: 1, subject: 'Physics', year: 2020),
  Question(question: 'Which of the following is a good conductor of electricity?', options: ['Glass', 'Rubber', 'Copper', 'Wood'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'The transformer works on the principle of:', options: ['Electrostatics', 'Electromagnetic induction', 'Photoelectric effect', 'Thermionic emission'], correctIndex: 1, subject: 'Physics', year: 2020),
  Question(question: 'The energy stored in a stretched spring is:', options: ['Kinetic energy', 'Thermal energy', 'Elastic potential energy', 'Chemical energy'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'Sound travels fastest in:', options: ['Air', 'Water', 'Steel', 'Vacuum'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'A concave mirror is used in:', options: ['Rear-view mirrors', 'Searchlights', 'Periscopes', 'Kaleidoscopes'], correctIndex: 1, subject: 'Physics', year: 2020),
  Question(question: 'The law of conservation of energy states that energy can be:', options: ['Created but not destroyed', 'Destroyed but not created', 'Neither created nor destroyed', 'Both created and destroyed'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'The unit of electrical resistance is:', options: ['Volt', 'Ampere', 'Ohm', 'Watt'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'Which of the following best describes inertia?', options: ['The force of gravity', 'The tendency of a body to resist change in motion', 'The energy of a moving body', 'The momentum of a body'], correctIndex: 1, subject: 'Physics', year: 2020),
  Question(question: 'The pitch of a sound is determined by its:', options: ['Amplitude', 'Frequency', 'Wavelength', 'Speed'], correctIndex: 1, subject: 'Physics', year: 2020),
  Question(question: 'Which of the following is an example of projectile motion?', options: ['A car moving in a straight line', 'A ball thrown horizontally', 'A lift moving upward', 'A pendulum swinging'], correctIndex: 1, subject: 'Physics', year: 2020),
  Question(question: 'The change in velocity per unit time is called:', options: ['Speed', 'Distance', 'Acceleration', 'Displacement'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'Latent heat of vaporisation is the heat required to:', options: ['Melt a solid', 'Convert liquid to gas at constant temperature', 'Raise temperature of a liquid', 'Freeze a liquid'], correctIndex: 1, subject: 'Physics', year: 2020),
  Question(question: 'The image formed by a plane mirror is:', options: ['Real and inverted', 'Virtual and inverted', 'Real and upright', 'Virtual and upright'], correctIndex: 3, subject: 'Physics', year: 2020),
  Question(question: 'Which of the following waves is longitudinal?', options: ['Light waves', 'Water waves', 'Sound waves', 'Radio waves'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'The unit of momentum is:', options: ['kg/m', 'kg⋅m/s', 'kg⋅m/s²', 'N/m'], correctIndex: 1, subject: 'Physics', year: 2020),
  Question(question: 'An object weighs 60 N on Earth. Its mass is approximately: (g = 10 m/s²)', options: ['6 kg', '60 kg', '600 kg', '0.6 kg'], correctIndex: 0, subject: 'Physics', year: 2020),
  Question(question: 'Boyle\'s Law states that at constant temperature, pressure is:', options: ['Directly proportional to volume', 'Inversely proportional to volume', 'Equal to volume', 'Independent of volume'], correctIndex: 1, subject: 'Physics', year: 2020),
  Question(question: 'The bending of waves around obstacles is called:', options: ['Reflection', 'Refraction', 'Diffraction', 'Interference'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'Work done is zero when the force applied is:', options: ['Very large', 'Perpendicular to displacement', 'Parallel to displacement', 'In the direction of motion'], correctIndex: 1, subject: 'Physics', year: 2020),
  Question(question: 'Which particle in the atom has no charge?', options: ['Proton', 'Electron', 'Neutron', 'Positron'], correctIndex: 2, subject: 'Physics', year: 2020),
  Question(question: 'Radioactive decay in which an electron is emitted is called:', options: ['Alpha decay', 'Beta decay', 'Gamma decay', 'Nuclear fission'], correctIndex: 1, subject: 'Physics', year: 2020),
  Question(question: 'The SI unit of charge is:', options: ['Ampere', 'Volt', 'Coulomb', 'Farad'], correctIndex: 2, subject: 'Physics', year: 2020),
];

// ── WAEC Physics 2021 ─────────────────────────────────────────────────────────
const List<Question> physicsQuestions2021 = [
  Question(question: 'A body moving in a circle at constant speed has:', options: ['Zero acceleration', 'Constant velocity', 'Centripetal acceleration', 'Zero force'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'The principle of moments states that for a body in equilibrium, the sum of clockwise moments equals:', options: ['Zero', 'Sum of anticlockwise moments', 'The weight of the body', 'The applied force'], correctIndex: 1, subject: 'Physics', year: 2021),
  Question(question: 'Which of the following has the shortest wavelength?', options: ['Radio waves', 'Infrared waves', 'Visible light', 'Gamma rays'], correctIndex: 3, subject: 'Physics', year: 2021),
  Question(question: 'The specific heat capacity of a substance is the heat needed to raise the temperature of:', options: ['1 kg by 1°C', '1 g by 100°C', '100 g by 1°C', '1 kg by 100°C'], correctIndex: 0, subject: 'Physics', year: 2021),
  Question(question: 'A step-up transformer increases:', options: ['Current', 'Voltage', 'Power', 'Frequency'], correctIndex: 1, subject: 'Physics', year: 2021),
  Question(question: 'The half-life of a radioactive substance is the time taken for:', options: ['All atoms to decay', 'Half the atoms to decay', 'One atom to decay', 'The substance to double'], correctIndex: 1, subject: 'Physics', year: 2021),
  Question(question: 'Archimedes\' principle states that the upthrust on a body equals:', options: ['The weight of the body', 'The weight of fluid displaced', 'The volume of the body', 'The density of the fluid'], correctIndex: 1, subject: 'Physics', year: 2021),
  Question(question: 'The SI unit of magnetic flux density is:', options: ['Weber', 'Tesla', 'Henry', 'Farad'], correctIndex: 1, subject: 'Physics', year: 2021),
  Question(question: 'In a series circuit, the current through each component is:', options: ['Different', 'The same', 'Zero', 'Maximum'], correctIndex: 1, subject: 'Physics', year: 2021),
  Question(question: 'Which of the following best describes a virtual image?', options: ['Can be projected on a screen', 'Cannot be projected on a screen', 'Is always inverted', 'Is always magnified'], correctIndex: 1, subject: 'Physics', year: 2021),
  Question(question: 'The formula for gravitational potential energy is:', options: ['½mv²', 'mgh', 'mv', 'Fd'], correctIndex: 1, subject: 'Physics', year: 2021),
  Question(question: 'A mirage is caused by:', options: ['Reflection of light', 'Diffraction of light', 'Total internal reflection', 'Interference of light'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'The frequency of the mains supply in Nigeria is:', options: ['50 Hz', '60 Hz', '100 Hz', '220 Hz'], correctIndex: 0, subject: 'Physics', year: 2021),
  Question(question: 'Which of the following is NOT an electromagnetic wave?', options: ['X-rays', 'Gamma rays', 'Sound waves', 'Ultraviolet rays'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'The loudness of sound depends on its:', options: ['Frequency', 'Wavelength', 'Amplitude', 'Speed'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'Hooke\'s Law states that extension is proportional to:', options: ['Mass', 'Weight', 'Applied force (within elastic limit)', 'Length of spring'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'Electromagnetic waves travel at the speed of light because they are:', options: ['Mechanical waves', 'Transverse waves', 'Not mechanical waves', 'Longitudinal waves'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'The number of protons in an atom is called its:', options: ['Mass number', 'Atomic number', 'Neutron number', 'Nucleon number'], correctIndex: 1, subject: 'Physics', year: 2021),
  Question(question: 'A body thrown upward decelerates due to:', options: ['Air resistance only', 'Gravity only', 'Both gravity and air resistance', 'Inertia'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'The refractive index of a medium is the ratio of:', options: ['Speed in medium to speed in vacuum', 'Speed in vacuum to speed in medium', 'Wavelength to frequency', 'Angle of incidence to angle of refraction'], correctIndex: 1, subject: 'Physics', year: 2021),
  Question(question: 'Nuclear fission involves:', options: ['Combining of nuclei', 'Splitting of nuclei', 'Emission of electrons', 'Absorption of neutrons'], correctIndex: 1, subject: 'Physics', year: 2021),
  Question(question: 'The unit of capacitance is:', options: ['Henry', 'Ohm', 'Farad', 'Tesla'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'Velocity is different from speed because velocity has:', options: ['Magnitude only', 'Direction only', 'Both magnitude and direction', 'Neither magnitude nor direction'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'Which instrument is used to measure small lengths accurately?', options: ['Metre rule', 'Tape measure', 'Vernier calliper', 'Barometer'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'The process of heat transfer without a material medium is:', options: ['Conduction', 'Convection', 'Radiation', 'Evaporation'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'An electric fuse is made of a material with:', options: ['High melting point', 'Low melting point', 'High resistance', 'Low conductivity'], correctIndex: 1, subject: 'Physics', year: 2021),
  Question(question: 'The critical angle is the angle of incidence in the denser medium when the angle of refraction is:', options: ['0°', '45°', '90°', '180°'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'A guitar string vibrates to produce sound. This is an example of:', options: ['Forced vibration', 'Resonance', 'Damping', 'Free vibration'], correctIndex: 3, subject: 'Physics', year: 2021),
  Question(question: 'The efficiency of a machine is always less than 100% because of:', options: ['Friction', 'Gravity', 'Air pressure', 'Inertia'], correctIndex: 0, subject: 'Physics', year: 2021),
  Question(question: 'Fleming\'s left-hand rule is used to determine the direction of:', options: ['Induced EMF', 'Force on a current-carrying conductor in a magnetic field', 'Magnetic field around a wire', 'Electric field'], correctIndex: 1, subject: 'Physics', year: 2021),
  Question(question: 'The wavelength of a wave is the distance between:', options: ['Two crests', 'A crest and a trough', 'Two successive compressions', 'Any two points'], correctIndex: 0, subject: 'Physics', year: 2021),
  Question(question: 'Which of the following is a renewable energy source?', options: ['Coal', 'Natural gas', 'Solar energy', 'Nuclear energy'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'The image formed in a pinhole camera is:', options: ['Virtual and upright', 'Real and upright', 'Real and inverted', 'Virtual and inverted'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'Power in an electrical circuit is given by:', options: ['P = V/I', 'P = VI', 'P = V + I', 'P = V - I'], correctIndex: 1, subject: 'Physics', year: 2021),
  Question(question: 'The turning effect of a force about a pivot is called:', options: ['Work', 'Energy', 'Moment of force (torque)', 'Impulse'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'When white light passes through a prism, it splits into colours. This is called:', options: ['Diffraction', 'Interference', 'Dispersion', 'Polarisation'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'Which of the following is used in a cathode ray oscilloscope (CRO)?', options: ['Proton beam', 'Electron beam', 'Neutron beam', 'Photon beam'], correctIndex: 1, subject: 'Physics', year: 2021),
  Question(question: 'The period of a pendulum depends on:', options: ['Mass of bob and length', 'Length only', 'Mass only', 'Amplitude only'], correctIndex: 1, subject: 'Physics', year: 2021),
  Question(question: 'A body at rest has:', options: ['Kinetic energy only', 'Potential energy only', 'Both kinetic and potential energy', 'No energy'], correctIndex: 1, subject: 'Physics', year: 2021),
  Question(question: 'Isotopes are atoms of the same element with the same atomic number but different:', options: ['Proton number', 'Electron number', 'Mass number', 'Charge'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'The SI unit of force is:', options: ['Joule', 'Pascal', 'Newton', 'Watt'], correctIndex: 2, subject: 'Physics', year: 2021),
  Question(question: 'The image of an object placed at the centre of curvature of a concave mirror is:', options: ['At infinity', 'At the focus', 'At the centre of curvature', 'Behind the mirror'], correctIndex: 2, subject: 'Physics', year: 2021),
];

// ── WAEC Physics 2022 ─────────────────────────────────────────────────────────
const List<Question> physicsQuestions2022 = [
  Question(question: 'A ball is dropped from a height. Just before hitting the ground, it has:', options: ['Maximum potential energy', 'Maximum kinetic energy', 'Zero kinetic energy', 'Equal kinetic and potential energy'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'The unit of work done is:', options: ['Watt', 'Newton', 'Joule', 'Pascal'], correctIndex: 2, subject: 'Physics', year: 2022),
  Question(question: 'Which of the following radiations is NOT deflected by a magnetic field?', options: ['Alpha particles', 'Beta particles', 'Gamma rays', 'Cathode rays'], correctIndex: 2, subject: 'Physics', year: 2022),
  Question(question: 'The distance-time graph of a body moving at constant speed is:', options: ['A curved line', 'A horizontal line', 'A straight line with positive slope', 'A vertical line'], correctIndex: 2, subject: 'Physics', year: 2022),
  Question(question: 'Resistance of a conductor increases when its:', options: ['Length decreases', 'Cross-sectional area increases', 'Temperature increases', 'Temperature decreases'], correctIndex: 2, subject: 'Physics', year: 2022),
  Question(question: 'Which of the following phenomena proves the wave nature of light?', options: ['Photoelectric effect', 'Interference', 'Reflection', 'Refraction'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'The quantity of heat (Q) absorbed by a body is given by:', options: ['Q = mcT', 'Q = mc/T', 'Q = m/cT', 'Q = c/mT'], correctIndex: 0, subject: 'Physics', year: 2022),
  Question(question: 'In which state of matter do particles have the most kinetic energy?', options: ['Solid', 'Liquid', 'Gas', 'Plasma'], correctIndex: 2, subject: 'Physics', year: 2022),
  Question(question: 'A transformer has 200 turns in the primary coil and 1000 turns in the secondary coil. If the input voltage is 50 V, the output voltage is:', options: ['10 V', '250 V', '400 V', '500 V'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'The phenomenon where electrons are emitted from a metal surface when light falls on it is:', options: ['Thermionic emission', 'Photoelectric effect', 'Field emission', 'Secondary emission'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'When a stone is thrown horizontally, the horizontal velocity:', options: ['Increases', 'Decreases', 'Remains constant', 'Becomes zero'], correctIndex: 2, subject: 'Physics', year: 2022),
  Question(question: 'Capacitors in a circuit are used to:', options: ['Store charge', 'Increase resistance', 'Convert AC to DC', 'Amplify current'], correctIndex: 0, subject: 'Physics', year: 2022),
  Question(question: 'The echo of a sound is due to:', options: ['Refraction', 'Reflection', 'Diffraction', 'Absorption'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'The equation v = u + at is used for:', options: ['Circular motion', 'Uniform acceleration', 'Simple harmonic motion', 'Projectile motion'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'The velocity ratio of a machine is:', options: ['Load / Effort', 'Effort distance / Load distance', 'Work output / Work input', 'Load distance / Effort distance'], correctIndex: 3, subject: 'Physics', year: 2022),
  Question(question: 'Which of the following is a property of alpha particles?', options: ['High penetrating power', 'Negatively charged', 'Not deflected by magnetic field', 'Low ionising power'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'A liquid boils when its saturated vapour pressure equals:', options: ['Zero', 'Atmospheric pressure', 'Room temperature', 'The density of the liquid'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'Which of the following obeys the inverse square law?', options: ['Gravitational force', 'Normal force', 'Friction', 'Tension'], correctIndex: 0, subject: 'Physics', year: 2022),
  Question(question: 'The device that converts electrical energy to sound energy is:', options: ['Microphone', 'Loudspeaker', 'Amplifier', 'Generator'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'The refractive index of glass is 1.5. The critical angle is approximately:', options: ['30°', '42°', '45°', '60°'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'Hydraulic machines work on the principle that pressure in a liquid is:', options: ['Transmitted unequally', 'Transmitted equally in all directions', 'Zero at the surface', 'Greatest at the surface'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'An object of mass 5 kg moving at 4 m/s has kinetic energy of:', options: ['10 J', '20 J', '40 J', '80 J'], correctIndex: 2, subject: 'Physics', year: 2022),
  Question(question: 'Light from the sun reaches the Earth by:', options: ['Conduction', 'Convection', 'Radiation', 'Induction'], correctIndex: 2, subject: 'Physics', year: 2022),
  Question(question: 'The device used to detect radioactivity is:', options: ['Thermometer', 'Geiger-Müller tube', 'Galvanometer', 'Ammeter'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'A p-type semiconductor is formed by doping silicon with:', options: ['Phosphorus', 'Arsenic', 'Boron', 'Antimony'], correctIndex: 2, subject: 'Physics', year: 2022),
  Question(question: 'The velocity of a wave is related to frequency f and wavelength λ by:', options: ['v = f/λ', 'v = fλ', 'v = λ/f', 'v = f + λ'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'Which part of the eye controls the amount of light entering?', options: ['Retina', 'Lens', 'Iris', 'Cornea'], correctIndex: 2, subject: 'Physics', year: 2022),
  Question(question: 'The standard unit of temperature in the SI system is:', options: ['Celsius', 'Fahrenheit', 'Kelvin', 'Rankine'], correctIndex: 2, subject: 'Physics', year: 2022),
  Question(question: 'A wire of resistance R is cut into two equal halves. The resistance of each half is:', options: ['2R', 'R', 'R/2', 'R/4'], correctIndex: 2, subject: 'Physics', year: 2022),
  Question(question: 'Nuclear fusion occurs in:', options: ['Nuclear reactors', 'The Sun', 'Atomic bombs', 'Geiger counters'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'When a ray of light travels from glass to air, it bends:', options: ['Toward the normal', 'Away from the normal', 'Along the normal', 'Parallel to the surface'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'The magnetic effect of current was discovered by:', options: ['Faraday', 'Oersted', 'Ampere', 'Volta'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'The escape velocity from Earth\'s surface is approximately:', options: ['7.9 km/s', '11.2 km/s', '9.8 km/s', '3×10⁸ m/s'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'Which of the following is a property of X-rays?', options: ['Cannot ionize gases', 'Travel at speed less than light', 'Cannot penetrate flesh', 'Travel in straight lines'], correctIndex: 3, subject: 'Physics', year: 2022),
  Question(question: 'The moment of a force depends on:', options: ['Magnitude of force only', 'Perpendicular distance from pivot only', 'Both magnitude and perpendicular distance', 'Mass and acceleration'], correctIndex: 2, subject: 'Physics', year: 2022),
  Question(question: 'An n-type semiconductor has excess of:', options: ['Holes', 'Protons', 'Electrons', 'Neutrons'], correctIndex: 2, subject: 'Physics', year: 2022),
  Question(question: 'When two parallel resistors have values R₁ and R₂, the combined resistance is:', options: ['R₁ + R₂', '(R₁ × R₂)/(R₁ + R₂)', 'R₁ - R₂', '(R₁ + R₂)/(R₁ × R₂)'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'The SI unit of pressure is:', options: ['Newton', 'Joule', 'Pascal', 'Bar'], correctIndex: 2, subject: 'Physics', year: 2022),
  Question(question: 'Which property of a wave changes when it passes from one medium to another?', options: ['Frequency', 'Speed', 'Period', 'Phase'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'Impulse is defined as:', options: ['Force × time', 'Force × distance', 'Mass × velocity', 'Force / time'], correctIndex: 0, subject: 'Physics', year: 2022),
  Question(question: 'The dew point is the temperature at which:', options: ['Water boils', 'Air becomes saturated with water vapour', 'Ice melts', 'Condensation stops'], correctIndex: 1, subject: 'Physics', year: 2022),
  Question(question: 'The image formed by a diverging lens is always:', options: ['Real and inverted', 'Real and upright', 'Virtual and upright', 'Virtual and inverted'], correctIndex: 2, subject: 'Physics', year: 2022),
];

// ── WAEC Physics 2023 ─────────────────────────────────────────────────────────
const List<Question> physicsQuestions2023 = [
  Question(question: 'The work-energy theorem states that the net work done on a body equals:', options: ['Its potential energy', 'Its change in kinetic energy', 'Its momentum', 'Its weight times height'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'A body performing simple harmonic motion has maximum velocity at:', options: ['The extreme ends', 'The equilibrium position', 'Halfway from equilibrium', 'The turning points'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'Which of the following is used to measure relative humidity?', options: ['Barometer', 'Hygrometer', 'Thermometer', 'Manometer'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'The ratio of output power to input power of a machine expressed as a percentage is:', options: ['Velocity ratio', 'Mechanical advantage', 'Efficiency', 'Load ratio'], correctIndex: 2, subject: 'Physics', year: 2023),
  Question(question: 'Which gate gives an output of 1 only when all inputs are 0?', options: ['AND gate', 'OR gate', 'NOR gate', 'NAND gate'], correctIndex: 2, subject: 'Physics', year: 2023),
  Question(question: 'When light passes through a double slit, it produces:', options: ['Dispersion', 'Polarisation', 'Interference fringes', 'Total internal reflection'], correctIndex: 2, subject: 'Physics', year: 2023),
  Question(question: 'The time taken for a complete oscillation of a pendulum is called its:', options: ['Frequency', 'Amplitude', 'Period', 'Wavelength'], correctIndex: 2, subject: 'Physics', year: 2023),
  Question(question: 'The Doppler effect refers to:', options: ['Change in speed of sound', 'Change in apparent frequency due to motion', 'Echo of sound', 'Reflection of sound'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'Ohm\'s law is valid only for:', options: ['All conductors', 'Ohmic conductors', 'Semiconductors', 'Insulators'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'The force between two charges is governed by:', options: ['Newton\'s Law', 'Coulomb\'s Law', 'Ohm\'s Law', 'Faraday\'s Law'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'A rectifier converts:', options: ['DC to AC', 'AC to DC', 'Low voltage to high voltage', 'Mechanical to electrical energy'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'The minimum angle of deviation in a prism occurs when the ray passes:', options: ['Normally through one face', 'Symmetrically through the prism', 'At the critical angle', 'Parallel to the base'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'Which quantity is conserved in an elastic collision?', options: ['Kinetic energy only', 'Momentum only', 'Both kinetic energy and momentum', 'Velocity only'], correctIndex: 2, subject: 'Physics', year: 2023),
  Question(question: 'The threshold frequency in photoelectric effect is:', options: ['The minimum frequency needed to eject electrons', 'The maximum frequency of emitted electrons', 'The frequency of emitted photons', 'The frequency at which no electrons are emitted'], correctIndex: 0, subject: 'Physics', year: 2023),
  Question(question: 'Gamma radiation is:', options: ['A stream of electrons', 'A stream of helium nuclei', 'High-energy electromagnetic radiation', 'Low-energy radiation'], correctIndex: 2, subject: 'Physics', year: 2023),
  Question(question: 'The formula for the period of a simple pendulum is:', options: ['T = 2π√(g/l)', 'T = 2π√(l/g)', 'T = 2π√(m/k)', 'T = 2πl/g'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'A body of mass 2 kg is lifted 5 m. The work done against gravity is: (g = 10 m/s²)', options: ['10 J', '25 J', '100 J', '50 J'], correctIndex: 2, subject: 'Physics', year: 2023),
  Question(question: 'Charles\'s Law states that at constant pressure, volume is:', options: ['Inversely proportional to temperature', 'Directly proportional to absolute temperature', 'Independent of temperature', 'Equal to temperature'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'The main advantage of optical fibre over copper wire in communications is:', options: ['Lower cost', 'Transmits light signals with less loss', 'Easier to install', 'Stronger material'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'Which of the following is a use of infrared radiation?', options: ['X-ray imaging', 'Remote controls', 'UV sterilisation', 'Cancer treatment'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'In a p-n junction diode, conventional current flows from:', options: ['n-type to p-type', 'p-type to n-type', 'Both directions equally', 'Neither direction'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'The energy of a photon is given by:', options: ['E = mv²', 'E = hf', 'E = mgh', 'E = ½mv²'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'Total internal reflection occurs when light:', options: ['Passes from less dense to denser medium', 'Passes from denser to less dense medium beyond critical angle', 'Hits a mirror', 'Passes through a prism'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'A solenoid carrying current behaves like:', options: ['A capacitor', 'A bar magnet', 'A resistor', 'A rectifier'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'The Bernoulli effect explains why:', options: ['Objects sink in water', 'Planes can fly', 'Magnets attract iron', 'Light refracts'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'In a full-wave rectifier, the number of diodes used is:', options: ['1', '2', '4', '6'], correctIndex: 2, subject: 'Physics', year: 2023),
  Question(question: 'The binding energy of a nucleus is:', options: ['Energy released during fission', 'Energy needed to completely separate all nucleons', 'Energy of electrons in the atom', 'Energy of gamma rays emitted'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'Which of the following is a vector quantity?', options: ['Mass', 'Time', 'Temperature', 'Weight'], correctIndex: 3, subject: 'Physics', year: 2023),
  Question(question: 'In electromagnetic induction, the induced EMF depends on:', options: ['Rate of change of magnetic flux', 'Total magnetic flux only', 'Current in the coil', 'Resistance of the coil'], correctIndex: 0, subject: 'Physics', year: 2023),
  Question(question: 'A body moving with uniform velocity has:', options: ['Zero acceleration', 'Increasing speed', 'Net force acting on it', 'Decreasing momentum'], correctIndex: 0, subject: 'Physics', year: 2023),
  Question(question: 'Which of the following has the highest penetrating power?', options: ['Alpha particles', 'Beta particles', 'Gamma rays', 'Cathode rays'], correctIndex: 2, subject: 'Physics', year: 2023),
  Question(question: 'The potential difference across a resistor of 5 Ω carrying 2 A is:', options: ['2.5 V', '7 V', '10 V', '15 V'], correctIndex: 2, subject: 'Physics', year: 2023),
  Question(question: 'Convection currents are caused by:', options: ['Radiation', 'Difference in density due to temperature change', 'Conduction between particles', 'Pressure differences only'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'The SI unit of inductance is:', options: ['Farad', 'Ohm', 'Henry', 'Tesla'], correctIndex: 2, subject: 'Physics', year: 2023),
  Question(question: 'An ammeter is connected in a circuit in:', options: ['Parallel', 'Series', 'Either series or parallel', 'Star configuration'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'The surface tension of a liquid is caused by:', options: ['Gravity', 'Cohesive forces between molecules', 'Adhesive forces', 'Buoyancy'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'A body of weight 100 N rests on a surface. The normal reaction of the surface is:', options: ['50 N', '100 N', '200 N', 'Zero'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'Which colour of visible light has the longest wavelength?', options: ['Violet', 'Green', 'Yellow', 'Red'], correctIndex: 3, subject: 'Physics', year: 2023),
  Question(question: 'A voltmeter is connected in a circuit in:', options: ['Series', 'Parallel', 'Both series and parallel', 'Delta configuration'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'The audible frequency range for humans is approximately:', options: ['0–200 Hz', '20–20,000 Hz', '200–20,000 Hz', '20–200 Hz'], correctIndex: 1, subject: 'Physics', year: 2023),
  Question(question: 'Lenz\'s Law is a consequence of the law of conservation of:', options: ['Charge', 'Mass', 'Energy', 'Momentum'], correctIndex: 2, subject: 'Physics', year: 2023),
];

// ── WAEC Physics 2024 ─────────────────────────────────────────────────────────
const List<Question> physicsQuestions2024 = [
  Question(question: 'A car accelerates from rest to 20 m/s in 5 s. Its acceleration is:', options: ['2 m/s²', '4 m/s²', '5 m/s²', '100 m/s²'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'The work done by a force of 10 N over a displacement of 5 m is:', options: ['2 J', '15 J', '50 J', '500 J'], correctIndex: 2, subject: 'Physics', year: 2024),
  Question(question: 'Which of the following is the correct unit of electric field strength?', options: ['N/C or V/m', 'V/A', 'C/V', 'N⋅m'], correctIndex: 0, subject: 'Physics', year: 2024),
  Question(question: 'The critical temperature of a superconductor is:', options: ['The temperature at which resistance becomes infinite', 'The temperature at which resistance becomes zero', 'The melting point', 'Room temperature'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'De Broglie\'s hypothesis states that moving particles have:', options: ['Wave-like properties', 'Only particle properties', 'No energy', 'Constant wavelength'], correctIndex: 0, subject: 'Physics', year: 2024),
  Question(question: 'The resolving power of a telescope increases when:', options: ['The objective lens diameter decreases', 'The wavelength of light used increases', 'The objective lens diameter increases', 'The eyepiece is removed'], correctIndex: 2, subject: 'Physics', year: 2024),
  Question(question: 'In a transistor, the base current controls:', options: ['The emitter voltage', 'The collector current', 'The supply voltage', 'The base resistance'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'The Bohr model of the atom was based on:', options: ['Wave mechanics', 'Quantum mechanics', 'Electrons in fixed orbits with quantised energy', 'Random motion of electrons'], correctIndex: 2, subject: 'Physics', year: 2024),
  Question(question: 'Which of the following is an application of nuclear energy?', options: ['Hydroelectric power', 'Nuclear power plants', 'Wind turbines', 'Solar panels'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'The mass defect in a nucleus represents:', options: ['Missing protons', 'Energy released during nuclear reactions', 'Excess neutrons', 'Radioactive decay products'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'When a spring of spring constant k is compressed by x, the elastic PE stored is:', options: ['kx', '2kx', '½kx²', 'kx²'], correctIndex: 2, subject: 'Physics', year: 2024),
  Question(question: 'A satellite in orbit is kept in circular motion by:', options: ['Thrust from engines', 'Gravitational force acting as centripetal force', 'Air resistance', 'Magnetic force'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'The photoelectric effect cannot be explained by:', options: ['Wave theory of light', 'Quantum theory of light', 'Particle theory of light', 'Photon theory'], correctIndex: 0, subject: 'Physics', year: 2024),
  Question(question: 'Which of the following gates is called the universal gate?', options: ['AND', 'OR', 'NAND', 'XOR'], correctIndex: 2, subject: 'Physics', year: 2024),
  Question(question: 'The Hall effect is used to:', options: ['Measure magnetic field strength', 'Detect radioactivity', 'Measure temperature', 'Generate electricity'], correctIndex: 0, subject: 'Physics', year: 2024),
  Question(question: 'A body is launched at 45° to the horizontal. The range is maximum when:', options: ['Angle is 30°', 'Angle is 45°', 'Angle is 60°', 'Angle is 90°'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'The charge on an electron is approximately:', options: ['1.6×10⁻¹⁹ C', '1.6×10¹⁹ C', '9.1×10⁻³¹ C', '1.67×10⁻²⁷ C'], correctIndex: 0, subject: 'Physics', year: 2024),
  Question(question: 'Superposition of waves occurs when:', options: ['Two waves collide and disappear', 'Two or more waves meet and their displacements add up', 'Waves change speed', 'Waves change frequency'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'The density of a liquid can be measured using:', options: ['A barometer', 'A hydrometer', 'A thermometer', 'A galvanometer'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'In AC circuits, the opposition to current flow by inductors is called:', options: ['Resistance', 'Capacitive reactance', 'Inductive reactance', 'Impedance'], correctIndex: 2, subject: 'Physics', year: 2024),
  Question(question: 'Which type of lens is used to correct myopia (short-sightedness)?', options: ['Convex lens', 'Concave lens', 'Bifocal lens', 'Cylindrical lens'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'Einstein\'s mass-energy equation is:', options: ['E = mgh', 'E = mc²', 'E = hf', 'E = ½mv²'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'Which of the following is true about stationary waves?', options: ['Energy is transmitted along the wave', 'Nodes are points of maximum displacement', 'Antinodes have zero displacement', 'No energy is transmitted'], correctIndex: 3, subject: 'Physics', year: 2024),
  Question(question: 'The time constant of an RC circuit is:', options: ['R + C', 'R × C', 'R / C', 'R - C'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'Which of the following is a use of ultrasound?', options: ['Night vision cameras', 'Medical imaging (sonography)', 'Radio communication', 'Laser surgery'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'The gradient of a velocity-time graph gives:', options: ['Distance', 'Speed', 'Acceleration', 'Displacement'], correctIndex: 2, subject: 'Physics', year: 2024),
  Question(question: 'A proton has a mass approximately equal to:', options: ['9.1×10⁻³¹ kg', '1.67×10⁻²⁷ kg', '1.6×10⁻¹⁹ kg', '6.63×10⁻³⁴ kg'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'The sensitivity of a galvanometer can be increased by:', options: ['Increasing the coil resistance', 'Increasing the number of turns in the coil', 'Decreasing the magnetic field', 'Using a stiffer suspension'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'In photoelectric emission, the stopping potential is used to measure:', options: ['The intensity of light', 'The maximum kinetic energy of emitted electrons', 'The frequency of light', 'The wavelength of light'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'Resonance in a circuit occurs when:', options: ['Resistance equals zero', 'Inductive reactance equals capacitive reactance', 'Current is zero', 'Voltage is maximum'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'The angular momentum of a planet around the sun is conserved due to:', options: ['Conservation of energy', 'Conservation of charge', 'No torque acting on the planet', 'Gravity'], correctIndex: 2, subject: 'Physics', year: 2024),
  Question(question: 'Which of the following correctly describes terminal velocity?', options: ['Maximum velocity when acceleration equals g', 'Constant velocity when drag force equals weight', 'Velocity at the end of motion', 'Velocity just before impact'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'The dimension of pressure is:', options: ['MLT⁻²', 'ML⁻¹T⁻²', 'ML²T⁻²', 'MLT⁻¹'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'The instrument used to measure the EMF of a cell accurately is:', options: ['Ammeter', 'Voltmeter', 'Potentiometer', 'Galvanometer'], correctIndex: 2, subject: 'Physics', year: 2024),
  Question(question: 'X-rays are produced when:', options: ['Electrons are emitted from hot cathode', 'Fast electrons are suddenly decelerated', 'Protons collide with nuclei', 'Alpha particles are emitted'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'The speed of sound in air at 0°C is approximately:', options: ['300 m/s', '330 m/s', '360 m/s', '400 m/s'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'A body in free fall experiences:', options: ['Zero weight and zero mass', 'Weight but apparent weightlessness', 'No gravitational force', 'Increased mass'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'The principle used in a hydraulic press is:', options: ['Archimedes\' principle', 'Pascal\'s principle', 'Bernoulli\'s principle', 'Newton\'s principle'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'Kirchhoff\'s current law states that:', options: ['Voltage drops sum to zero in a loop', 'The sum of currents entering a junction equals sum leaving', 'Current is constant in all resistors', 'EMF equals sum of all resistances'], correctIndex: 1, subject: 'Physics', year: 2024),
  Question(question: 'In Young\'s double-slit experiment, fringe width increases when:', options: ['Wavelength decreases', 'Slit separation increases', 'Distance to screen increases', 'Slit width increases'], correctIndex: 2, subject: 'Physics', year: 2024),
  Question(question: 'Which physical quantity has the dimension ML²T⁻³?', options: ['Force', 'Energy', 'Power', 'Pressure'], correctIndex: 2, subject: 'Physics', year: 2024),
];

// ── WAEC Physics 2025 ─────────────────────────────────────────────────────────
const List<Question> physicsQuestions2025 = [
  Question(question: 'An object of mass 4 kg is moving at 3 m/s. Its momentum is:', options: ['1.33 kg⋅m/s', '7 kg⋅m/s', '12 kg⋅m/s', '36 kg⋅m/s'], correctIndex: 2, subject: 'Physics', year: 2025),
  Question(question: 'The gravitational field strength at a point is defined as:', options: ['Force per unit charge', 'Force per unit mass', 'Energy per unit mass', 'Acceleration times mass'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'A wave has a frequency of 500 Hz and wavelength 0.68 m. Its speed is:', options: ['0.00136 m/s', '340 m/s', '500 m/s', '73.5 m/s'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'Which of the following is a use of gamma rays?', options: ['TV broadcasting', 'Cancer treatment (radiotherapy)', 'Night vision', 'Remote sensing'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'The internal resistance of an ideal voltage source is:', options: ['Infinite', 'Zero', 'Equal to external resistance', '1 Ohm'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'Polarisation of light proves that light is a:', options: ['Longitudinal wave', 'Transverse wave', 'Mechanical wave', 'Sound wave'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'The work function in photoelectric effect is:', options: ['The kinetic energy of electrons', 'The minimum energy required to eject an electron from a metal surface', 'The energy of the photon', 'The frequency of light'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'The period of a wave is related to its frequency by:', options: ['T = f', 'T = 1/f', 'T = f²', 'T = 2πf'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'Which of the following is an application of the Doppler effect?', options: ['Periscope', 'Telescope', 'Speed gun (radar)', 'Microscope'], correctIndex: 2, subject: 'Physics', year: 2025),
  Question(question: 'An electric charge of 3 C passes through a wire in 6 s. The current is:', options: ['18 A', '9 A', '2 A', '0.5 A'], correctIndex: 3, subject: 'Physics', year: 2025),
  Question(question: 'The property of a material to return to its original shape after deformation is called:', options: ['Plasticity', 'Ductility', 'Elasticity', 'Brittleness'], correctIndex: 2, subject: 'Physics', year: 2025),
  Question(question: 'Friction between surfaces can be reduced by:', options: ['Increasing the weight of objects', 'Lubrication', 'Using rough surfaces', 'Increasing surface area'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'The output of a NOT gate when input is 0 is:', options: ['0', '1', 'Undefined', '2'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'In nuclear notation ²³⁸₉₂U, the number of neutrons is:', options: ['92', '146', '238', '330'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'The phenomenon where a wave loses energy as it travels is called:', options: ['Amplification', 'Attenuation', 'Interference', 'Diffraction'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'A body of mass 10 kg falls freely from rest. After 3 s, its velocity is: (g = 10 m/s²)', options: ['3 m/s', '10 m/s', '30 m/s', '90 m/s'], correctIndex: 2, subject: 'Physics', year: 2025),
  Question(question: 'Which of the following is correct for a body in uniform circular motion?', options: ['Speed changes, velocity constant', 'Both speed and velocity constant', 'Speed constant, velocity changes', 'Both speed and velocity change'], correctIndex: 2, subject: 'Physics', year: 2025),
  Question(question: 'The ratio Ns/Np = Vs/Vp in a transformer is based on:', options: ['Faraday\'s law of electrolysis', 'Mutual induction', 'Self-induction', 'Coulomb\'s law'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'Which of the following is NOT a use of radioactivity?', options: ['Medical diagnosis', 'Carbon dating', 'Food preservation', 'Solar energy generation'], correctIndex: 3, subject: 'Physics', year: 2025),
  Question(question: 'The centre of gravity of a uniform rectangular lamina is:', options: ['At one corner', 'At the midpoint of one side', 'At the intersection of the diagonals', 'At the longest side'], correctIndex: 2, subject: 'Physics', year: 2025),
  Question(question: 'The first law of thermodynamics states that:', options: ['Heat flows from cold to hot bodies', 'Energy cannot be created or destroyed', 'Entropy always increases', 'Temperature is proportional to pressure'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'A conductor of length L carrying current I in a magnetic field B experiences a force:', options: ['F = BIL', 'F = B/IL', 'F = I/BL', 'F = IL/B'], correctIndex: 0, subject: 'Physics', year: 2025),
  Question(question: 'Standing waves are formed by:', options: ['Two waves of different frequencies', 'Superposition of two identical waves travelling in opposite directions', 'A single wave bouncing back and forth', 'Two waves of different amplitudes'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'Capillarity is the rise or fall of liquid in a narrow tube due to:', options: ['Gravity alone', 'Surface tension and adhesion/cohesion', 'Pressure difference', 'Density difference'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'The power dissipated in a resistor of resistance R carrying current I is:', options: ['P = IR', 'P = I²R', 'P = I/R', 'P = IR²'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'A current-carrying conductor placed in a magnetic field will experience a force if the current is:', options: ['Parallel to the field', 'Perpendicular to the field', 'At 180° to the field', 'Zero'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'The Heisenberg uncertainty principle states that we cannot simultaneously and precisely measure:', options: ['Mass and velocity', 'Position and momentum', 'Charge and mass', 'Energy and charge'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'An echo requires a minimum distance of about:', options: ['10 m', '17 m', '34 m', '50 m'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'The specific latent heat of fusion of ice is approximately:', options: ['2260 kJ/kg', '336 kJ/kg', '4200 J/kg⋅K', '100 kJ/kg'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'Which of the following is NOT a property of electric field lines?', options: ['They start from positive charges', 'They can intersect each other', 'They end on negative charges', 'They show direction of force on positive charge'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'The output voltage of a full-wave rectifier has a frequency:', options: ['Equal to input frequency', 'Twice the input frequency', 'Half the input frequency', 'Zero'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'The de Broglie wavelength λ of a particle of momentum p is:', options: ['λ = hp', 'λ = h/p', 'λ = p/h', 'λ = h²/p'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'A parachutist reaches terminal velocity when:', options: ['Weight equals air resistance', 'Weight is greater than air resistance', 'Air resistance is zero', 'Speed is maximum possible'], correctIndex: 0, subject: 'Physics', year: 2025),
  Question(question: 'Which of the following best defines magnetic flux?', options: ['Magnetic field times current', 'Magnetic field times area', 'Magnetic field divided by area', 'Force per unit charge'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'The phenomenon of beats is produced by superposition of two sound waves of:', options: ['Same frequency', 'Very different frequencies', 'Slightly different frequencies', 'Different amplitudes only'], correctIndex: 2, subject: 'Physics', year: 2025),
  Question(question: 'For a concave mirror, if the object is placed beyond the centre of curvature, the image is:', options: ['Virtual and magnified', 'Real, inverted and diminished', 'Real, upright and magnified', 'At infinity'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'The Geiger-Müller tube detects radiation by measuring:', options: ['Temperature changes', 'Ionisation of gas inside the tube', 'Magnetic deflection', 'Optical fluorescence'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'Young\'s modulus is a measure of:', options: ['Elasticity of a material', 'Tensile stress divided by tensile strain', 'Strength of a material', 'Both A and B'], correctIndex: 3, subject: 'Physics', year: 2025),
  Question(question: 'The force of friction on a body on a horizontal surface is equal to:', options: ['μmg', 'mg', 'μm', 'mg/μ'], correctIndex: 0, subject: 'Physics', year: 2025),
  Question(question: 'In a p-n junction diode under reverse bias:', options: ['Large current flows', 'Only a small leakage current flows', 'No current flows at all', 'The diode is destroyed'], correctIndex: 1, subject: 'Physics', year: 2025),
  Question(question: 'If the distance between two charges is doubled, the electrostatic force becomes:', options: ['4 times larger', '2 times larger', '4 times smaller', '2 times smaller'], correctIndex: 2, subject: 'Physics', year: 2025),
];

// ══════════════════════════════════════════════════════════════════════════════
// COMBINED PHYSICS OBJECTIVE QUESTIONS
// ══════════════════════════════════════════════════════════════════════════════
const List<Question> allPhysicsQuestions = [
  ...physicsQuestions2020,
  ...physicsQuestions2021,
  ...physicsQuestions2022,
  ...physicsQuestions2023,
  ...physicsQuestions2024,
  ...physicsQuestions2025,
];

// ══════════════════════════════════════════════════════════════════════════════
// THEORY QUESTIONS
// ══════════════════════════════════════════════════════════════════════════════
const List<TheoryQuestion> physicsTheoryQuestions = [

  // ── 2020 Theory ──────────────────────────────────────────────────────────────
  TheoryQuestion(
    question: '(a) State Newton\'s second law of motion.\n(b) A force of 20 N acts on a body of mass 4 kg initially at rest. Calculate:\n   (i) The acceleration of the body\n   (ii) The velocity after 5 seconds\n   (iii) The distance covered in 5 seconds.',
    answer: '(a) Newton\'s Second Law: The rate of change of momentum of a body is directly proportional to the applied force and takes place in the direction of the force.\n\n(b)(i) F = ma → a = F/m = 20/4 = 5 m/s²\n\n(ii) v = u + at = 0 + 5×5 = 25 m/s\n\n(iii) s = ut + ½at² = 0 + ½×5×25 = 62.5 m',
    subject: 'Physics', year: 2020,
  ),
  TheoryQuestion(
    question: '(a) State Ohm\'s Law.\n(b) Three resistors of 2 Ω, 3 Ω, and 6 Ω are connected in parallel across a 12 V battery.\n   (i) Find the total resistance\n   (ii) Find the total current drawn from the battery\n   (iii) Find the current through the 6 Ω resistor.',
    answer: '(a) Ohm\'s Law: The current through a conductor is directly proportional to the potential difference across it, provided temperature and other physical conditions remain constant. V = IR.\n\n(b)(i) 1/Rt = 1/2 + 1/3 + 1/6 = 3/6 + 2/6 + 1/6 = 6/6 = 1\nRt = 1 Ω\n\n(ii) I = V/R = 12/1 = 12 A\n\n(iii) I₆ = V/R₆ = 12/6 = 2 A',
    subject: 'Physics', year: 2020,
  ),
  TheoryQuestion(
    question: '(a) Define the following:\n   (i) Wavelength\n   (ii) Frequency\n   (iii) Wave speed\n(b) A wave has a frequency of 400 Hz and a wavelength of 0.85 m. Calculate its speed.\n(c) State TWO differences between transverse and longitudinal waves.',
    answer: '(a)(i) Wavelength: The distance between two consecutive points in phase on a wave (e.g. crest to crest).\n(ii) Frequency: The number of complete oscillations per second. Unit: Hertz (Hz).\n(iii) Wave speed: The distance travelled by the wave per unit time.\n\n(b) v = fλ = 400 × 0.85 = 340 m/s\n\n(c) Differences:\n1. Transverse waves: vibrations perpendicular to direction of propagation. Longitudinal waves: vibrations parallel to direction of propagation.\n2. Transverse waves can be polarised; longitudinal waves cannot.\n3. Examples: Transverse – light, water. Longitudinal – sound.',
    subject: 'Physics', year: 2020,
  ),
  TheoryQuestion(
    question: '(a) State the law of conservation of energy.\n(b) A stone of mass 0.5 kg is dropped from a height of 20 m. Calculate:\n   (i) The potential energy at the top\n   (ii) The kinetic energy just before hitting the ground\n   (iii) The velocity just before hitting the ground\n(Take g = 10 m/s²)',
    answer: '(a) Energy cannot be created or destroyed; it can only be converted from one form to another. The total energy of an isolated system remains constant.\n\n(b)(i) PE = mgh = 0.5 × 10 × 20 = 100 J\n\n(ii) By conservation of energy: KE = PE = 100 J\n\n(iii) KE = ½mv² → v² = 2KE/m = 2×100/0.5 = 400\nv = √400 = 20 m/s',
    subject: 'Physics', year: 2020,
  ),

  // ── 2021 Theory ──────────────────────────────────────────────────────────────
  TheoryQuestion(
    question: '(a) State Archimedes\' Principle.\n(b) A metal block weighs 80 N in air and 60 N when fully submerged in water. Calculate:\n   (i) The upthrust on the block\n   (ii) The volume of the block (density of water = 1000 kg/m³, g = 10 m/s²)\n   (iii) The density of the metal.',
    answer: '(a) Archimedes\' Principle: When a body is wholly or partially immersed in a fluid, it experiences an upthrust equal to the weight of the fluid displaced.\n\n(b)(i) Upthrust = Weight in air - Weight in water = 80 - 60 = 20 N\n\n(ii) Upthrust = ρ_water × V × g\n20 = 1000 × V × 10\nV = 20/10000 = 2×10⁻³ m³\n\n(iii) Mass of metal = 80/10 = 8 kg\nDensity = m/V = 8/(2×10⁻³) = 4000 kg/m³',
    subject: 'Physics', year: 2021,
  ),
  TheoryQuestion(
    question: '(a) Explain the following types of radioactive decay:\n   (i) Alpha decay\n   (ii) Beta decay\n   (iii) Gamma emission\n(b) A radioactive substance has a half-life of 20 years. If the initial mass is 80 g, calculate the mass remaining after 80 years.',
    answer: '(a)(i) Alpha decay: The nucleus emits an alpha particle (₂⁴He), reducing atomic number by 2 and mass number by 4.\n(ii) Beta decay: A neutron in the nucleus converts to a proton, emitting a beta particle (electron ₋₁⁰e), increasing atomic number by 1.\n(iii) Gamma emission: After alpha or beta decay, excess energy is released as a high-energy gamma ray photon. No change in atomic or mass number.\n\n(b) Number of half-lives = 80/20 = 4\nMass remaining = 80 × (½)⁴ = 80 × 1/16 = 5 g',
    subject: 'Physics', year: 2021,
  ),
  TheoryQuestion(
    question: '(a) State Hooke\'s Law.\n(b) A spring extends by 4 cm when a force of 8 N is applied. Calculate:\n   (i) The spring constant\n   (ii) The extension when a force of 20 N is applied\n   (iii) The elastic potential energy stored when the spring is extended by 10 cm.',
    answer: '(a) Hooke\'s Law: The extension of a spring is directly proportional to the applied force, provided the elastic limit is not exceeded. F = ke\n\n(b)(i) k = F/e = 8/0.04 = 200 N/m\n\n(ii) e = F/k = 20/200 = 0.1 m = 10 cm\n\n(iii) EPE = ½ke² = ½ × 200 × (0.1)² = ½ × 200 × 0.01 = 1 J',
    subject: 'Physics', year: 2021,
  ),

  // ── 2022 Theory ──────────────────────────────────────────────────────────────
  TheoryQuestion(
    question: '(a) Explain the photoelectric effect.\n(b) State TWO observations in the photoelectric effect that cannot be explained by the wave theory of light.\n(c) The threshold frequency of a metal is 5×10¹⁴ Hz. Calculate:\n   (i) The work function of the metal\n   (ii) The maximum kinetic energy of electrons when light of frequency 7×10¹⁴ Hz is used.\n(h = 6.63×10⁻³⁴ Js)',
    answer: '(a) The photoelectric effect is the emission of electrons from a metal surface when electromagnetic radiation of sufficient frequency falls on it.\n\n(b) Wave theory cannot explain:\n1. The existence of a threshold frequency (wave theory predicts any frequency could eject electrons given enough time)\n2. The instantaneous emission of electrons (wave theory predicts a time delay for enough energy to accumulate)\n\n(c)(i) W = hf₀ = 6.63×10⁻³⁴ × 5×10¹⁴\n= 3.315×10⁻¹⁹ J\n\n(ii) KE_max = hf - W = 6.63×10⁻³⁴×7×10¹⁴ - 3.315×10⁻¹⁹\n= 4.641×10⁻¹⁹ - 3.315×10⁻¹⁹\n= 1.326×10⁻¹⁹ J',
    subject: 'Physics', year: 2022,
  ),
  TheoryQuestion(
    question: '(a) State Boyle\'s Law and Charles\'s Law.\n(b) A gas occupies a volume of 400 cm³ at 27°C and 100 kPa pressure. Calculate the volume it will occupy at 127°C and 200 kPa pressure.\n(c) State TWO assumptions of the kinetic theory of gases.',
    answer: '(a) Boyle\'s Law: At constant temperature, the volume of a fixed mass of gas is inversely proportional to its pressure. PV = constant.\nCharles\'s Law: At constant pressure, the volume of a fixed mass of gas is directly proportional to its absolute temperature. V/T = constant.\n\n(b) Using combined gas law: P₁V₁/T₁ = P₂V₂/T₂\nT₁ = 27 + 273 = 300 K, T₂ = 127 + 273 = 400 K\nV₂ = P₁V₁T₂/(T₁P₂) = (100×400×400)/(300×200)\n= 16,000,000/60,000 = 266.7 cm³\n\n(c) Assumptions:\n1. Gas molecules are in constant random motion\n2. Collisions between molecules are perfectly elastic\n3. The volume of the molecules is negligible compared to the container',
    subject: 'Physics', year: 2022,
  ),
  TheoryQuestion(
    question: '(a) Describe how a step-up transformer works.\n(b) A transformer has 400 turns in its primary coil and is connected to a 240 V AC supply. If the secondary has 2000 turns, find:\n   (i) The output voltage\n   (ii) If the secondary current is 0.5 A, calculate the primary current (assume 100% efficiency)\n   (iii) State ONE reason why transformers cannot work with DC supply.',
    answer: '(a) A step-up transformer increases voltage. It works by electromagnetic induction. When an AC current flows through the primary coil, it creates a changing magnetic flux in the iron core. This changing flux induces an EMF in the secondary coil. Since the secondary has more turns than the primary, the induced voltage is higher.\n\n(b)(i) Vs/Vp = Ns/Np\nVs = (Ns/Np) × Vp = (2000/400) × 240 = 5 × 240 = 1200 V\n\n(ii) Assuming 100% efficiency: VpIp = VsIs\nIp = (Vs × Is)/Vp = (1200 × 0.5)/240 = 600/240 = 2.5 A\n\n(iii) DC produces a constant magnetic flux that does not change, so no EMF is induced in the secondary coil. Transformers require a changing magnetic flux which only AC provides.',
    subject: 'Physics', year: 2022,
  ),

  // ── 2023 Theory ──────────────────────────────────────────────────────────────
  TheoryQuestion(
    question: '(a) State Newton\'s law of universal gravitation.\n(b) The mass of the Earth is 6×10²⁴ kg and its radius is 6.4×10⁶ m. Calculate:\n   (i) The gravitational field strength at the Earth\'s surface (G = 6.67×10⁻¹¹ Nm²/kg²)\n   (ii) The weight of a 70 kg person on Earth\n   (iii) The orbital velocity of a satellite just above the Earth\'s surface.',
    answer: '(a) Newton\'s Law of Universal Gravitation: Every particle of matter attracts every other particle with a force directly proportional to the product of their masses and inversely proportional to the square of the distance between them.\nF = Gm₁m₂/r²\n\n(b)(i) g = GM/r² = (6.67×10⁻¹¹ × 6×10²⁴)/(6.4×10⁶)²\n= 4.002×10¹⁴/4.096×10¹³ ≈ 9.77 ≈ 9.8 m/s²\n\n(ii) W = mg = 70 × 9.8 = 686 N\n\n(iii) For orbital velocity: mv²/r = GMm/r²\nv = √(GM/r) = √(6.67×10⁻¹¹×6×10²⁴/6.4×10⁶)\n= √(6.254×10⁷) ≈ 7908 m/s ≈ 7.9 km/s',
    subject: 'Physics', year: 2023,
  ),
  TheoryQuestion(
    question: '(a) Define:\n   (i) Specific heat capacity\n   (ii) Latent heat of vaporisation\n(b) Calculate the heat required to:\n   (i) Raise the temperature of 2 kg of water from 20°C to 100°C\n   (ii) Convert the water to steam at 100°C\n(Specific heat capacity of water = 4200 J/kg⋅K, Latent heat of vaporisation = 2.26×10⁶ J/kg)',
    answer: '(a)(i) Specific heat capacity: The amount of heat required to raise the temperature of 1 kg of a substance by 1 K (or 1°C).\n(ii) Latent heat of vaporisation: The heat required to change 1 kg of a liquid to vapour at constant temperature.\n\n(b)(i) Q₁ = mcΔT = 2 × 4200 × (100-20)\n= 2 × 4200 × 80 = 672,000 J = 672 kJ\n\n(ii) Q₂ = mL = 2 × 2.26×10⁶ = 4.52×10⁶ J = 4520 kJ\n\nTotal heat = Q₁ + Q₂ = 672 + 4520 = 5192 kJ',
    subject: 'Physics', year: 2023,
  ),

  // ── 2024 Theory ──────────────────────────────────────────────────────────────
  TheoryQuestion(
    question: '(a) State Faraday\'s laws of electromagnetic induction.\n(b) A coil of 200 turns is placed in a magnetic field. The magnetic flux through the coil changes from 0.05 Wb to 0.02 Wb in 0.3 s. Calculate:\n   (i) The rate of change of magnetic flux\n   (ii) The induced EMF\n(c) State Lenz\'s Law and explain how it relates to energy conservation.',
    answer: '(a) Faraday\'s Laws:\n1st: Whenever the magnetic flux through a circuit changes, an EMF is induced in the circuit.\n2nd: The magnitude of the induced EMF is directly proportional to the rate of change of magnetic flux linkage.\nEMF = -N(dΦ/dt)\n\n(b)(i) Rate of change of flux = ΔΦ/Δt = (0.05-0.02)/0.3 = 0.03/0.3 = 0.1 Wb/s\n\n(ii) EMF = N × ΔΦ/Δt = 200 × 0.1 = 20 V\n\n(c) Lenz\'s Law: The induced current flows in a direction such that it opposes the change that caused it.\nRelation to energy conservation: If the induced current aided the change, it would create a self-sustaining loop of energy increase, violating conservation of energy. By opposing the change, work must be done to maintain the flux change, ensuring energy is conserved.',
    subject: 'Physics', year: 2024,
  ),
  TheoryQuestion(
    question: '(a) Explain what is meant by total internal reflection.\n(b) State the conditions necessary for total internal reflection to occur.\n(c) The refractive index of glass is 1.5. Calculate:\n   (i) The critical angle for glass\n   (ii) The speed of light in glass (speed of light in vacuum = 3×10⁸ m/s)\n(d) State TWO practical applications of total internal reflection.',
    answer: '(a) Total internal reflection occurs when a ray of light travels from a denser medium to a less dense medium and hits the boundary at an angle greater than the critical angle. All the light is reflected back into the denser medium — none passes through.\n\n(b) Conditions:\n1. Light must travel from a denser medium to a less dense medium\n2. The angle of incidence must be greater than the critical angle\n\n(c)(i) sin C = 1/n = 1/1.5 = 0.667\nC = sin⁻¹(0.667) ≈ 41.8°\n\n(ii) n = c/v → v = c/n = 3×10⁸/1.5 = 2×10⁸ m/s\n\n(d) Applications:\n1. Optical fibres (used in telecommunications and endoscopes)\n2. Periscopes and binoculars (using prisms)\n3. Diamonds (cut to maximise internal reflection for brilliance)',
    subject: 'Physics', year: 2024,
  ),
  TheoryQuestion(
    question: '(a) A body of mass 3 kg is attached to a string of length 2 m and whirled in a horizontal circle.\n   (i) If it completes 5 revolutions per second, find the angular velocity\n   (ii) Calculate the linear velocity\n   (iii) Calculate the centripetal force\n   (iv) Calculate the centripetal acceleration\n(b) State what provides the centripetal force for a satellite orbiting the Earth.',
    answer: '(a)(i) Angular velocity ω = 2πf = 2π × 5 = 10π ≈ 31.4 rad/s\n\n(ii) Linear velocity v = ωr = 31.4 × 2 = 62.8 m/s\n\n(iii) Centripetal force F = mv²/r = mω²r\n= 3 × (31.4)² × 2 = 3 × 985.96 × 2 ≈ 5916 N\n\n(iv) Centripetal acceleration a = v²/r = (62.8)²/2 = 3943.84/2 ≈ 1972 m/s²\n\n(b) Gravity (gravitational attraction between the satellite and the Earth) provides the centripetal force needed to keep the satellite in orbit.',
    subject: 'Physics', year: 2024,
  ),

  // ── 2025 Theory ──────────────────────────────────────────────────────────────
  TheoryQuestion(
    question: '(a) State the laws of refraction of light (Snell\'s Law).\n(b) A ray of light passes from air (n=1) into glass at an angle of incidence of 30°. The refractive index of glass is 1.5. Calculate:\n   (i) The angle of refraction\n   (ii) The speed of light in glass\n   (iii) The wavelength of light in glass if its wavelength in air is 600 nm.',
    answer: '(a) Laws of Refraction (Snell\'s Law):\n1. The incident ray, refracted ray, and normal all lie in the same plane.\n2. The ratio of the sine of the angle of incidence to the sine of the angle of refraction is constant for a given pair of media:\nn₁ sin θ₁ = n₂ sin θ₂\n\n(b)(i) n₁ sin θ₁ = n₂ sin θ₂\n1 × sin 30° = 1.5 × sin θ₂\nsin θ₂ = 0.5/1.5 = 0.333\nθ₂ = sin⁻¹(0.333) ≈ 19.5°\n\n(ii) v = c/n = 3×10⁸/1.5 = 2×10⁸ m/s\n\n(iii) λ_glass = λ_air/n = 600/1.5 = 400 nm',
    subject: 'Physics', year: 2025,
  ),
  TheoryQuestion(
    question: '(a) Explain nuclear fission and nuclear fusion.\n(b) State TWO similarities and TWO differences between fission and fusion.\n(c) Calculate the energy released when a mass of 2×10⁻³ kg is converted to energy. (c = 3×10⁸ m/s)\n(d) State TWO advantages and ONE disadvantage of nuclear energy.',
    answer: '(a) Nuclear Fission: The splitting of a heavy nucleus (e.g. uranium-235) into two lighter nuclei when struck by a neutron, releasing a large amount of energy and more neutrons.\nNuclear Fusion: The combining of two light nuclei (e.g. deuterium and tritium) at very high temperatures to form a heavier nucleus, releasing even more energy.\n\n(b) Similarities:\n1. Both release enormous amounts of energy\n2. Both involve changes in nuclear mass (mass defect)\n\nDifferences:\n1. Fission: splits heavy nuclei; Fusion: combines light nuclei\n2. Fission occurs at room temperature (triggered by neutrons); Fusion requires extremely high temperatures (~10⁷ K)\n\n(c) E = mc² = 2×10⁻³ × (3×10⁸)²\n= 2×10⁻³ × 9×10¹⁶\n= 1.8×10¹⁴ J\n\n(d) Advantages:\n1. Produces enormous amounts of energy from small amounts of fuel\n2. Does not produce greenhouse gases during operation\n\nDisadvantage:\n1. Produces radioactive waste that is difficult to dispose of safely',
    subject: 'Physics', year: 2025,
  ),
  TheoryQuestion(
    question: '(a) Describe an experiment to verify Ohm\'s Law.\n(b) In a circuit, a battery of EMF 12 V and internal resistance 1 Ω is connected to an external resistor of 5 Ω. Calculate:\n   (i) The current in the circuit\n   (ii) The terminal voltage of the battery\n   (iii) The power dissipated in the external resistor\n   (iv) The power lost internally.',
    answer: '(a) Experiment to verify Ohm\'s Law:\nApparatus: Battery, rheostat, resistor, ammeter (in series), voltmeter (in parallel with resistor), switch.\nMethod: Vary the resistance of the rheostat. For each setting, record the current I (ammeter) and voltage V (voltmeter). Plot a graph of V against I. A straight line through the origin confirms Ohm\'s Law (V ∝ I), and the slope gives the resistance R.\n\n(b)(i) I = EMF/(R + r) = 12/(5 + 1) = 12/6 = 2 A\n\n(ii) Terminal voltage = EMF - Ir = 12 - 2×1 = 10 V\n(or V = IR = 2×5 = 10 V ✓)\n\n(iii) P_external = I²R = 2² × 5 = 4 × 5 = 20 W\n\n(iv) P_internal = I²r = 2² × 1 = 4 W',
    subject: 'Physics', year: 2025,
  ),
];